name: Validate

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      # ruby/setup-ruby@v1 does not offer a way to change the cached gems path.
      # See https://github.com/ruby/setup-ruby/issues/291
      GLOBAL_GEMS: 1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
        cache-version: 2

    - name: Build & Validate
      run: rake validate

  changes:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' }}
    permissions:
      pull-requests: read
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          docker:
            - '_config.yml'
            - '.dockerignore'
            - '*docker*'
            - 'Dockerfile'
            - 'Gemfile*'
            - 'package*.json'
            - 'Rakefile'

  docker:
    needs: changes
    if: ${{ needs.changes.outputs.docker == 'true' }} || ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build container
      run: docker-compose build

    - name: Build site in container
      run: docker-compose run docs rake build
